// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID        uuid.UUID
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	Email          string
}

type VersionedNote struct {
	Title         string
	Content       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	NoteID        uuid.UUID
	VersionNumber int32
}
