// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNewNote = `-- name: CreateNewNote :one

Insert into notes (title, content , updated_at)
Values ($1,$2 , NOW())
Returning id, title, content, created_at, updated_at
`

type CreateNewNoteParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateNewNote(ctx context.Context, arg CreateNewNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNewNote, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :one
Delete from notes
where id = $1
returning id, title, content, created_at, updated_at
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, deleteNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getANote = `-- name: GetANote :one

Select 
    id,
    title,
    content,
    updated_at
  from notes
where id = $1
`

type GetANoteRow struct {
	ID        uuid.UUID
	Title     string
	Content   string
	UpdatedAt time.Time
}

func (q *Queries) GetANote(ctx context.Context, id uuid.UUID) (GetANoteRow, error) {
	row := q.db.QueryRowContext(ctx, getANote, id)
	var i GetANoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllNotes = `-- name: GetAllNotes :many

Select 
     id ,
    title,
    content,
    updated_at
From notes
`

type GetAllNotesRow struct {
	ID        uuid.UUID
	Title     string
	Content   string
	UpdatedAt time.Time
}

func (q *Queries) GetAllNotes(ctx context.Context) ([]GetAllNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNotesRow
	for rows.Next() {
		var i GetAllNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one

update notes
Set 
    title = $2,
    content = $3,
    updated_at = NOW()
where id = $1
returning id, title, content, created_at, updated_at
`

type UpdateNoteParams struct {
	ID      uuid.UUID
	Title   string
	Content string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.ID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
