// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNewNote = `-- name: CreateNewNote :one

Insert into notes (title, content , updated_at , owner_id)
Values ($1,$2 , NOW() , $3)
Returning owner_id , id , created_at
`

type CreateNewNoteParams struct {
	Title   string
	Content string
	OwnerID uuid.UUID
}

type CreateNewNoteRow struct {
	OwnerID   uuid.UUID
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateNewNote(ctx context.Context, arg CreateNewNoteParams) (CreateNewNoteRow, error) {
	row := q.db.QueryRowContext(ctx, createNewNote, arg.Title, arg.Content, arg.OwnerID)
	var i CreateNewNoteRow
	err := row.Scan(&i.OwnerID, &i.ID, &i.CreatedAt)
	return i, err
}

const deleteNote = `-- name: DeleteNote :one
Delete from notes
where id = $1 and owner_id = $2 
returning id
`

type DeleteNoteParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteNote, arg.ID, arg.OwnerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getANote = `-- name: GetANote :one

Select 
    id,
    title,
    content,
    updated_at
    owner_id
  from notes
where id = $1 and owner_id = $2
`

type GetANoteParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type GetANoteRow struct {
	ID      uuid.UUID
	Title   string
	Content string
	OwnerID time.Time
}

func (q *Queries) GetANote(ctx context.Context, arg GetANoteParams) (GetANoteRow, error) {
	row := q.db.QueryRowContext(ctx, getANote, arg.ID, arg.OwnerID)
	var i GetANoteRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.OwnerID,
	)
	return i, err
}

const getAllNotes = `-- name: GetAllNotes :many

Select 
     id ,
    title,
    content,
    updated_at,
    owner_id
From notes where owner_id = $1
`

type GetAllNotesRow struct {
	ID        uuid.UUID
	Title     string
	Content   string
	UpdatedAt time.Time
	OwnerID   uuid.UUID
}

func (q *Queries) GetAllNotes(ctx context.Context, ownerID uuid.UUID) ([]GetAllNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllNotes, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNotesRow
	for rows.Next() {
		var i GetAllNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one

update notes
Set 
    title = $2,
    content = $3,
    updated_at = NOW()
where id = $1 and owner_id = $4
returning id, title, content, created_at, updated_at, owner_id
`

type UpdateNoteParams struct {
	ID      uuid.UUID
	Title   string
	Content string
	OwnerID uuid.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.OwnerID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
