// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

insert Into users(id,updated_at, hashed_password , email)
values (
  gen_random_uuid(),
  NOW(),
  $2,
  $1
)
returning
id,
email,
created_at
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one

Select id, hashed_password, created_at
from users where email = $1
`

type FindUserByEmailRow struct {
	ID             uuid.UUID
	HashedPassword string
	CreatedAt      time.Time
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(&i.ID, &i.HashedPassword, &i.CreatedAt)
	return i, err
}
