// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versioned_notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAVersion = `-- name: CreateAVersion :one

Insert into versioned_notes(note_id,version_number,title,content,updated_at)
Values(
  $1,
  $2,
  $3,
  $4,
  NOW()
) 
returning note_id,version_number,updated_at
`

type CreateAVersionParams struct {
	NoteID        uuid.UUID
	VersionNumber int32
	Title         string
	Content       string
}

type CreateAVersionRow struct {
	NoteID        uuid.UUID
	VersionNumber int32
	UpdatedAt     time.Time
}

func (q *Queries) CreateAVersion(ctx context.Context, arg CreateAVersionParams) (CreateAVersionRow, error) {
	row := q.db.QueryRowContext(ctx, createAVersion,
		arg.NoteID,
		arg.VersionNumber,
		arg.Title,
		arg.Content,
	)
	var i CreateAVersionRow
	err := row.Scan(&i.NoteID, &i.VersionNumber, &i.UpdatedAt)
	return i, err
}

const getAllVersions = `-- name: GetAllVersions :many

Select version_number , created_at
From versioned_notes where note_id = $1
`

type GetAllVersionsRow struct {
	VersionNumber int32
	CreatedAt     time.Time
}

func (q *Queries) GetAllVersions(ctx context.Context, noteID uuid.UUID) ([]GetAllVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllVersions, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllVersionsRow
	for rows.Next() {
		var i GetAllVersionsRow
		if err := rows.Scan(&i.VersionNumber, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentHighestVersion = `-- name: GetCurrentHighestVersion :one

Select COALESCE(MAX(version_number) , 0)::INT
From versioned_notes 
where note_id = $1
`

func (q *Queries) GetCurrentHighestVersion(ctx context.Context, noteID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCurrentHighestVersion, noteID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getNoteVersion = `-- name: GetNoteVersion :one

Select title, content, created_at, updated_at, note_id, version_number From versioned_notes
where note_id = $1 and version_number = $2
`

type GetNoteVersionParams struct {
	NoteID        uuid.UUID
	VersionNumber int32
}

func (q *Queries) GetNoteVersion(ctx context.Context, arg GetNoteVersionParams) (VersionedNote, error) {
	row := q.db.QueryRowContext(ctx, getNoteVersion, arg.NoteID, arg.VersionNumber)
	var i VersionedNote
	err := row.Scan(
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NoteID,
		&i.VersionNumber,
	)
	return i, err
}
